### ISSUE TITLE
Don't call completionHandler

### ISSUE THREAD

**Issue by baltimor90** [filestack/filestack-swift#18] opened 2020-04-20 21:43 UTC
Hello,

I use FilestackSDK v2.2.1.
When i disabled internet before start loading, i get error in completionHandler. It's OK.
But if i start loading big file and disable internet when loading is executing, completionHandler not call. I wait above 5 minutes.

My options:
```
options: .init(
                            preferIntelligentIngestion: false,
                            startImmediately: true,
                            storeOptions: .defaults,
                            partUploadConcurrency: 1,
                            chunkUploadConcurrency: 1
                        ),
```

I investigate filestack lib code and found next case:
In MultifileUpload class, when loading is executing, executing uploadSubmitPartOperation in func doUploadFile().
When i disable internet after some seconds uploadSubmitPartOperation is finished and call checkpointOperation in func doUploadFile().
partOperation.didFail is true and shouldAbort is true, and perform next code:
```
if self.shouldAbort {
      self.uploadOperationQueue.cancelAllOperations()
}
```
But beforeCompleteCheckPointOperation not call, because cancelAllOperations, and don't call fail(with: MultipartUploadError.aborted)

When i change your code in checkpointOperation in func doUploadFile():
```
if self.shouldAbort {
      self.uploadOperationQueue.cancelAllOperations()
      self.fail(with: MultipartUploadError.aborted)
}
```
I will get error in completionHandler.

Can you help me with this case?

Thanks!

**Comment by rnine** [comment] 2020-04-22 10:54
@baltimor90 Hmm, I am unable to reproduce this issue.

> But beforeCompleteCheckPointOperation not call, because cancelAllOperations, and don't call fail(with: MultipartUploadError.aborted)

The completion block on `beforeCompleteCheckPointOperation` should always be called, regardless of whether the operations were cancelled or completed successfully. And that's exactly what I am seeing here when I am trying to reproduce the issue:

If I try to upload ~3MB, disable the connection, say after 700KB have finished uploading, the completion block on `beforeCompleteCheckPointOperation` is called and the upload's completion handler is called with a response containing error `FilestackSDK.MultipartUploadError.aborted`.

On a real device, this happens right after disconnecting. On the simulator, this happens after 1m timeout, but the result is still the same.

This is the relevant code I have used on a fresh iOS project (using latest FilestackSDK v2.2.1 as well):

```swift
let data = Data(repeating: 65, count: 32768 * 100)

let options = UploadOptions(
    preferIntelligentIngestion: false,
    startImmediately: true,
    storeOptions: .defaults,
    partUploadConcurrency: 1,
    chunkUploadConcurrency: 1
)

client?.upload(using: data, options: options) { (response) in
    print("Got response: \(response)")
}
```

@baltimor90 Could you please provide any further details on how to reproduce the exact issue you are describing?

**Comment by 0xNSHuman** [comment] 2020-04-24 18:11
Hey @rnine, thanks for your reply. I'm working around the same problem, and while I can reproduce this unresponsive behaviour @baltimor90 is talking about, we do see the `.aborted` error coming from Filestack in production from our users.

Now, another thing I wanted to ask you, is there a way Filestack could be more verbose as to what happened under the hood? It would be cool to have the error returned by the system or Alamofire or whatever propagated all the way up so we could collect some analytical data.

Appreciate your time, thanks.

**Comment by baltimor90** [comment] 2020-04-25 19:17
@rnine, thanks for your reply.

I try your example and really all is ok.

But i change your example on 

`let data = Data(repeating: 65, count: 32768 * 100*10)`

It is ~30MB. And chunkSize == 5242880, so we have more than one part.
Than i get case as in my first post in this topic.

Can you try uploading with ~30MB data?

Thanks!

**Comment by rnine** [comment] 2020-04-28 12:44
@baltimor90 Thanks! I was finally able to replicate the issue and implemented a solution that should work fine in all cases.

Would you be able to to test against the latest code in develop branch?

@vladaverin24 

> Now, another thing I wanted to ask you, is there a way Filestack could be more verbose as to what happened under the hood? It would be cool to have the error returned by the system or Alamofire or whatever propagated all the way up so we could collect some analytical data.
> 
> Appreciate your time, thanks.

Yes, error propagation should definitely be added. We'll definitely consider adding it — thanks for your feedback!

**Comment by baltimor90** [comment] 2020-04-29 23:45
@rnine i tested the latest code in develop branch.

In my case with 30 MB and disabling the Internet after uploading started:

After call partOperationQueue.cancelAllOperations() 
in all MultipartRegularUploadSubmitPartOperation call cancel func, 
but still next MultipartRegularUploadSubmitPartOperation in partOperationQueue call main() and next upload and waiting alamofire return error with disable internet.
I investigate this issues in you code and found two options:

1) in MultipartRegularUploadSubmitPartOperation update code in func upload():
```
guard !isCancelled || didFail else {
        state = .finished
        return
}
```
or

2) 
- in BaseOperation add call super.cancel in override func cancel()
- update to:
```
override var isFinished: Bool {
        return state == .finished || isCancelled
}
```

I have reproduced this issues in playground, watch console:

1) Playground with issues, looks like your implementation:
```

import UIKit
import PlaygroundSupport

PlaygroundPage.current.needsIndefiniteExecution = true


private let masterOperationQueue = OperationQueue()
private let partOperationQueue = OperationQueue()
partOperationQueue.maxConcurrentOperationCount = 1

class BaseOperation: Operation {
    enum State {
        case ready
        case executing
        case finished
    }
    
    let delay: Int
    var state = State.ready
    
    override var isReady: Bool {
        return state == .ready
    }

    override var isExecuting: Bool {
        return state == .executing
    }
    override var isFinished: Bool {
        return state == .finished
    }
    
    init(delay: Int) {
        self.delay = delay
        super.init()
    }
    
    override func main() {
        state = .executing
        sleep(UInt32(delay))
        print("BaseOperation end \(delay) operation")
        state = .finished
    }
    
    override func cancel() {
        if isExecuting {
            state = .finished
        }
    }
}


for i in 1...10 {
    let partOperation = BaseOperation(delay: i)
    
    let checkpointOperation = BlockOperation {
        print(partOperationQueue.operationCount)
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            print("partOperationQueue.cancelAllOperations()")
            partOperationQueue.cancelAllOperations()
        }
    }
    
    checkpointOperation.addDependency(partOperation)
    partOperationQueue.addOperation(partOperation)
    partOperationQueue.addOperation(checkpointOperation)
}


masterOperationQueue.addOperation {
    partOperationQueue.waitUntilAllOperationsAreFinished()
    
    print(partOperationQueue.operationCount)
    print("masterOperationQueue end operation")
}
```

2) Playground without issues:

```
import UIKit
import PlaygroundSupport

PlaygroundPage.current.needsIndefiniteExecution = true


private let masterOperationQueue = OperationQueue()
private let partOperationQueue = OperationQueue()
partOperationQueue.maxConcurrentOperationCount = 1

class BaseOperation: Operation {
    
    let delay: Int
    
    
    init(delay: Int) {
        self.delay = delay
        super.init()
    }
    
    override func main() {
        sleep(UInt32(delay))
        print("BaseOperation end \(delay) operation")
    }
}


for i in 1...10 {
    let partOperation = BaseOperation(delay: i)
    
    let checkpointOperation = BlockOperation {
        print(partOperationQueue.operationCount)
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            print("partOperationQueue.cancelAllOperations()")
            partOperationQueue.cancelAllOperations()
        }
    }
    
    checkpointOperation.addDependency(partOperation)
    partOperationQueue.addOperation(partOperation)
    partOperationQueue.addOperation(checkpointOperation)
}


masterOperationQueue.addOperation {
    partOperationQueue.waitUntilAllOperationsAreFinished()
    
    print(partOperationQueue.operationCount)
    print("masterOperationQueue end operation")
}
```

**Comment by rnine** [comment] 2020-04-30 09:21
@baltimor90 Thanks, I was able to replicate this new issue and I can see where the problem is. I went for a solution that implements the abort logic in `BaseOperation`'s `start()` and calls `super.cancel()` on the `cancel()` override (this is necessary so `isCancelled` is updated to `true` when `cancel()` is called.) Fix is included in https://github.com/filestack/filestack-swift/commit/8a6953990747d0aefc08e96da183614967b37cd7.

I think this is probably the best way to address this problem. Please let me know if this addresses the problem for you — thanks!

**Comment by baltimor90** [comment] 2020-05-01 17:24
@rnine I looked at new commit, all is OK. Thanks!

**Comment by rnine** [comment] 2020-05-04 08:42
@baltimor90 Excellent! I'll be preparing a new release today — thanks for reporting this bug!

**Closed as completed by rnine** 2020-05-04 08:42 UTC
